### PR TITLE
Add Teirese flag

### PR DESCRIPTION
**Pull request by SquareScreamYT**

### CODE REVIEW

**Comment by SquareScreamYT** [comment]
oh and lodeise flag too

**Comment by rgerum** [comment]
The flags seem to have an empty border on top and on the bottom as github shows it. That might cause problems when using them.
https://github.com/rgerum/unofficial-duolingo-stories/pull/232/files

**Comment by SquareScreamYT** [comment]
wdym?

**Comment by SquareScreamYT** [comment]
image

**Comment by rgerum** [comment]
image

**Comment by rgerum** [comment]
This is how it looks for me on github.

**Comment by Danika-Dakika** [comment]
Is it just my eyes, or does lodeise have a red border around the whole thing? 
image
image

And is the bottom edge of the gray on teirese bumpy? (Although admittedly it seems to disappear when I make the flag larger ...)
image

I don't know if these things will show when it's in use, but I'm used to cleaner lines for the flags.

**Comment by SquareScreamYT** [comment]
let me fix that real quick

**Comment by SquareScreamYT** [comment]
huh i will create a new pull request then (+barranquenho flag)

**Pull request closed without merging**
