### PR TITLE
Made the `Enter` to login function accurate

### PR DESCRIPTION
**Pull request by onfranciis**

### CODE REVIEW

**Comment by ptoro** [comment]
@onfranciis, event.keyCode is deprecated: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode.

I suggest using a modern approach such as the highest-voted answer here: https://stackoverflow.com/a/33212911/1101602.

**Comment by ptoro** [comment]
Hi @onfranciis, it looks like you may have combined two issues into the same pull request.

I suggest you check out this quick video course and follow the steps the instructor lays out: https://egghead.io/lessons/javascript-introduction-to-github

Let me know if you have any questions.

**Comment by onfranciis** [comment]
> Hi @onfranciis, it looks like you may have combined two issues into the same pull request.
> 
> I suggest you check out this quick video course and follow the steps the instructor lays out: https://egghead.io/lessons/javascript-introduction-to-github
> 
> Let me know if you have any questions.

Thanks for the link @ptoro

**Comment by rgerum** [comment]
Well if it is too much mess to rewind this I can also accept them together.
But I would like you to address the issue ptoro raised about keyCode being deprecated. Then I will be happy to merge it.

**Comment by onfranciis** [comment]
> Well if it is too much mess to rewind this I can also accept them together. But I would like you to address the issue ptoro raised about keyCode being deprecated. Then I will be happy to merge it.

I'll work on it now

**Comment by ptoro** [comment]
@onfranciis, I suggest creating a new pull request by following the steps laid out in the video course. That would be good practice for following the open source contribution workflow.

**Comment by ptoro** [comment]
@onfranciis, be sure to follow the instructions in the video from the beginning, taking care not to skip any steps, and you'll be able to create a new pull request without any issues.

**Comment by rgerum** [comment]
I think you need to create a new branch for a new pull request. And only put the commits for one pull request into each branch

**Comment by onfranciis** [comment]
> I think you need to create a new branch for a new pull request. And only put the commits for one pull request into each branch

Sounds like a good idea

**Pull request closed without merging**
