### PR TITLE
added incubator section for courses < 20 stories

### PR DESCRIPTION
**Pull request by rgerum**
To prevent the main page to be clustered with many small courses that might give a first impression that the duostories project is quite unfinished, I want to move the smaller courses to an "incubator" section.

### CODE REVIEW

**Comment by rgerum** [comment]
You can see a test deployment here: https://pr238.duostories.org/

**Comment by SquareScreamYT** [comment]
there is a missing 't' there, as in 'at'

image

**Comment by SquareScreamYT** [comment]
the courses also seem to be in a random order, and why is from in the brackets while the other language is not?

image

**Comment by rgerum** [comment]
The order of the courses it by number of stories, to see how "complete" they are. I also threw all the courses together into a single list and not separated them by base language, therefore I need the "from language". Oh but yes the parentheses are placed in a very random way :-D I need to change that. Thanks.

**Comment by rgerum** [comment]
image

**Pull request merged**
